import { useEffect, useRef, useState } from 'react';
import { BookOpen, Upload, Settings2, Share2, Download, X, Plus, FileText, ChevronRight, Sparkles, GraduationCap, RotateCcw, LoaderCircle, Check, Volume2, Library, AlertCircle, ArrowLeft, PanelLeft, Search, ArrowUpRight } from 'lucide-react';
import { actionSchemas, levels, languages, mastery, type Action, type Annotation, type LocalDocument, type Selection, type StudyPackResult } from '../shared/contracts';
import { api, exportPack, fingerprint, loadDocuments, saveDocuments, type Health } from './lib';
import PdfReader from './PdfReader';
import AnnotationCard, { actionIcons, actionLabels } from './AnnotationCard';
import Markdown from './Markdown';

function Modal({title,children,onClose}: {title:string;children:React.ReactNode;onClose:()=>void}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{ref.current?.showModal();},[]);
  return <dialog ref={ref} className="modal" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}}><div className="modal-heading"><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;
}
type Room = { id:string; documentId:string; documentName:string; annotations:Annotation[] };
type Preferences = { level:typeof levels[number]; language:typeof languages[number]; voiceId:string; autoNarrate:boolean; name:string; owner:string };
function initialPreferences(): Preferences {
  const defaults: Preferences={level:'Intermediate',language:'English',voiceId:'',autoNarrate:false,name:'You',owner:crypto.randomUUID()};
  try {const stored=JSON.parse(localStorage.getItem('lumen-preferences')||'{}');return {...defaults,...stored};}catch{return defaults;}
}
export default function App() {
  const [documents,setDocuments]=useState<LocalDocument[]>([]);const [currentId,setCurrentId]=useState('');const [restored,setRestored]=useState(false);
  const [view,setView]=useState<'library'|'reader'>('library');const [sidebarOpen,setSidebarOpen]=useState(true);const [search,setSearch]=useState('');
  const [page,setPage]=useState(1);const [selection,setSelection]=useState<Selection|null>(null);const [pageText,setPageText]=useState<string[]>([]);
  const [health,setHealth]=useState<Health|null>(null);const [prefs,setPrefs]=useState(initialPreferences);
  const [modal,setModal]=useState<'import'|'settings'|'share'|'insights'|'pack'|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');
  const [busy,setBusy]=useState<Action|null>(null);const [importing,setImporting]=useState(false);const [url,setUrl]=useState('');const [tab,setTab]=useState<'all'|'adapt'|'quiz'|'animate'|'review'>('all');
  const [voices,setVoices]=useState<{id:string;name:string}[]>([]);const [voiceLoading,setVoiceLoading]=useState(false);const [pack,setPack]=useState<StudyPackResult|null>(null);
  const [room,setRoom]=useState<Room|null>(null);const [shared,setShared]=useState<Annotation[]>([]);const [sharing,setSharing]=useState(false);const [copied,setCopied]=useState(false);
  const input=useRef<HTMLInputElement>(null);const initialized=useRef(false);const docsRef=useRef(documents);docsRef.current=documents;
  const saveQueue=useRef(Promise.resolve());const operation=useRef(false);
  const doc=documents.find(d=>d.id===currentId)||null;
  const ownIds=new Set(doc?.annotations.map(a=>a.id)||[]);
  const annotations=doc?[...doc.annotations,...shared.filter(a=>!ownIds.has(a.id))].sort((a,b)=>b.createdAt-a.createdAt):[];
  const score=mastery(doc?.annotations||[]);
  const due=annotations.filter(a=>a.type==='quiz'&&Object.values(a.reviewAt).some(t=>t>0&&t<=Date.now()));
  const voiceId=prefs.voiceId||health?.elevenlabs.voiceId||'';
  const roomId=doc?.roomId||(room?.documentId===doc?.id?room?.id:undefined);
  const onError=(message:string)=>{setError(message);setNotice('');};
  useEffect(()=>{
    if(initialized.current)return;initialized.current=true;
    void api<Health>('/health').then(setHealth).catch(e=>onError(e.message));
    void loadDocuments().then(saved=>{
      // Remove the old starter document; the library contains only uploaded PDFs.
      const list=saved.filter(d=>d.id!=='b52b43d322ad4ce3ba77c7ebd728060fff9635d5852c2681daedce0d973683fc');
      setDocuments(list);setCurrentId(list[0]?.id||'');setRestored(true);
    }).catch(e=>{onError(e.message);setRestored(true);});
    const id=new URLSearchParams(location.search).get('room');
    if(id)void api<Room>(`/rooms/${encodeURIComponent(id)}`).then(setRoom).catch(e=>onError(e.message));
  },[]);
  useEffect(()=>{if(!restored)return;saveQueue.current=saveQueue.current.then(()=>saveDocuments(documents)).catch(()=>onError('Your browser could not save this document. Export your study pack before closing.'));},[documents,restored]);
  useEffect(()=>{localStorage.setItem('lumen-preferences',JSON.stringify(prefs));},[prefs]);
  useEffect(()=>{setPage(1);setSelection(null);setPageText([]);setShared([]);setPack(null);},[currentId]);
  useEffect(()=>{if(room&&documents.some(d=>d.id===room.documentId)){setCurrentId(room.documentId);setView('reader');setDocuments(ds=>ds.map(d=>d.id===room.documentId?{...d,roomId:room.id}:d));}},[room?.id,documents.length]);
  useEffect(()=>{
    if(!roomId)return;let cancelled=false;
    const refresh=()=>api<Room>(`/rooms/${roomId}`).then(data=>{if(!cancelled)setShared(data.annotations);}).catch(e=>{if(!cancelled)onError(`Study room: ${e.message}`);});
    void refresh();const interval=setInterval(refresh,5000);return()=>{cancelled=true;clearInterval(interval);};
  },[roomId]);
  useEffect(()=>{if(!notice)return;const timeout=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(timeout);},[notice]);
  function updateDoc(id:string,fn:(d:LocalDocument)=>LocalDocument){setDocuments(ds=>ds.map(d=>d.id===id?fn(d):d));}
  async function syncAnnotation(a:Annotation,targetRoom=roomId){if(!targetRoom)return;try{await api(`/rooms/${targetRoom}/annotations`,{owner:prefs.owner,annotation:a});}catch(e){onError(`Saved locally, but sharing failed: ${(e as Error).message}`);}}
  function updateAnnotation(a:Annotation){updateDoc(a.documentId,d=>({...d,annotations:d.annotations.map(old=>old.id===a.id?a:old),updatedAt:Date.now()}));void syncAnnotation(a);}
  async function importBytes(bytes:Uint8Array,name:string){
    if(bytes.byteLength>30*1024*1024)throw new Error('Choose a PDF smaller than 30 MB.');
    const signature=new TextDecoder().decode(bytes.slice(0,1024));if(!signature.includes('%PDF-'))throw new Error('That file is not a PDF.');
    const id=await fingerprint(bytes);const existing=docsRef.current.find(d=>d.id===id);
    if(!existing){const d:LocalDocument={id,name:name.slice(0,300),bytes,pages:0,annotations:[],updatedAt:Date.now(),...(room?.documentId===id?{roomId:room.id}:{})};setDocuments(ds=>[d,...ds]);}
    setCurrentId(id);setView('reader');setModal(null);setSelection(null);setPage(1);setError('');
  }
  async function importFile(file:File){setImporting(true);try{await importBytes(new Uint8Array(await file.arrayBuffer()),file.name);}catch(e){onError((e as Error).message);}finally{setImporting(false);}}
  async function importUrl(){setImporting(true);try{const parsed=new URL(url);if(!['https:','http:'].includes(parsed.protocol))throw new Error('Use an http or https PDF link.');const response=await fetch(parsed.href,{credentials:'omit',referrerPolicy:'no-referrer',signal:AbortSignal.timeout(30000)});if(!response.ok)throw new Error('The PDF URL could not be loaded. Download it and upload the file.');const length=Number(response.headers.get('content-length'));if(length>30*1024*1024)throw new Error('Choose a PDF smaller than 30 MB.');await importBytes(new Uint8Array(await response.arrayBuffer()),decodeURIComponent(parsed.pathname.split('/').pop()||'Reading.pdf'));}catch(e){onError(e instanceof TypeError?'This website blocks direct PDF imports. Download the PDF and upload it.':(e as Error).message);}finally{setImporting(false);}}
  function contextFor(selected:Selection){return pageText.slice(0,selected.page).map((t,i)=>`[Page ${i+1}${i+1===selected.page?' — current page':''}] ${t}`).join('\n').slice(-40000);}
  async function generate(action:Action,source=selection){
    if(!doc||!source||operation.current)return;operation.current=true;setBusy(action);setError('');
    const documentId=doc.id;const targetRoom=roomId;
    try{
      const data=await api<unknown>(`/generate/${action}`,{selection:{text:source.text,page:source.page,image:source.image},level:prefs.level,language:prefs.language,context:contextFor(source)});
      const parsed=actionSchemas[action].parse(data);
      if(action==='study-pack'){setPack(parsed as StudyPackResult);return;}
      const annotation:Annotation={id:crypto.randomUUID(),documentId,type:action,author:prefs.name.trim()||'You',createdAt:Date.now(),selection:{text:source.text,page:source.page,rects:source.rects},data:parsed as Annotation['data'],answers:{},reviewAt:{},watched:false};
      updateDoc(documentId,d=>({...d,annotations:[annotation,...d.annotations],updatedAt:Date.now()}));setTab('all');await syncAnnotation(annotation,targetRoom);
    }catch(e){onError((e as Error).message);}finally{setBusy(null);operation.current=false;}
  }
  async function generatePack(){
    if(!doc||operation.current)return;operation.current=true;setModal('pack');setPack(null);setBusy('study-pack');setError('');
    try{
      const context=JSON.stringify(annotations.map(a=>({type:a.type,page:a.selection.page,passage:a.selection.text,data:a.data,answers:a.answers}))).slice(0,40000);
      const data=await api<unknown>('/generate/study-pack',{selection:{text:pageText.join('\n').slice(0,12000)||annotations.map(a=>a.selection.text).join('\n').slice(0,12000)||doc.name,page:1},context,level:prefs.level,language:prefs.language});
      setPack(actionSchemas['study-pack'].parse(data));
    }catch(e){onError((e as Error).message);}finally{setBusy(null);operation.current=false;}
  }
  async function share(){if(!doc||sharing)return;setSharing(true);setCopied(false);try{let id=roomId;if(!id){const created=await api<{id:string}>('/rooms',{documentId:doc.id,documentName:doc.name});id=created.id;updateDoc(doc.id,d=>({...d,roomId:id}));for(const a of doc.annotations)await syncAnnotation(a,id);}setModal('share');}catch(e){onError((e as Error).message);}finally{setSharing(false);}}
  const filtered=tab==='review'?due:annotations.filter(a=>tab==='all'||a.type===tab);
  return <div className={`app ${sidebarOpen?'':'sidebar-hidden'}`} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const file=e.dataTransfer.files[0];if(file)void importFile(file);}}>
    <input ref={input} type="file" accept="application/pdf,.pdf" hidden onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);e.target.value='';}}/>
    <header className="global-header"><button className="brand" onClick={()=>setView('library')} aria-label="Lumen library"><span className="brand-mark" aria-hidden="true">Ⅱ</span><strong>Lumen</strong><span>Reader</span></button>{view==='reader'&&<button className="icon-button panel-toggle" aria-label="Toggle pages sidebar" onClick={()=>setSidebarOpen(!sidebarOpen)}><PanelLeft size={20}/></button>}<button className={`nav-link ${view==='library'?'active':''}`} onClick={()=>setView('library')}>Library</button><div className="header-search"><Search size={18}/><input aria-label="Search your library" placeholder="Search your library" value={search} onChange={e=>{setSearch(e.target.value);setView('library');}}/></div><div className="header-actions"><button className="small-button" onClick={()=>setModal('import')}><Plus size={18}/><span>Import</span></button>{view==='reader'&&doc&&<button className="primary-button" disabled={!annotations.length||!!busy} onClick={generatePack}><Download size={16}/><span>Study pack</span></button>}<button className="profile-button" aria-label="Reader settings" onClick={()=>setModal('settings')}>{(prefs.name.trim()[0]||'Y').toUpperCase()}</button></div></header>
    <div className="app-messages">
      {error&&<div className="message error" role="alert"><AlertCircle size={18}/><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}
      {notice&&<div className="message success" role="status"><Check size={17}/><span>{notice}</span></div>}
      {room&&doc?.id!==room.documentId&&<div className="setup-banner"><Share2 size={17}/><span>To join this study room, import the same PDF: {room.documentName}.</span><button onClick={()=>input.current?.click()}>Import PDF</button></div>}
    </div>
    {view==='library'||!doc?<main className="library-page"><div className="library-heading"><div><h1>Your library</h1><p>{documents.length?`${documents.length} ${documents.length===1?'document':'documents'}`:'Your PDFs, notes, and ideas. In one place.'}</p></div>{documents.length>0&&<button className="small-button" onClick={()=>setModal('import')}><Plus size={17}/> Add a PDF</button>}</div>{documents.length?<div className="library-grid">{documents.filter(d=>d.name.toLowerCase().includes(search.toLowerCase())).map(d=><button className="document-tile" key={d.id} onClick={()=>{setCurrentId(d.id);setView('reader');setSelection(null);}}><div className="document-cover"><FileText size={42}/><span>PDF</span><strong>{d.name.replace(/\.pdf$/i,'')}</strong></div><h2>{d.name.replace(/\.pdf$/i,'')}</h2><p>{d.pages?`${d.pages} pages · `:''}{d.annotations.length} annotations</p></button>)}{!documents.some(d=>d.name.toLowerCase().includes(search.toLowerCase()))&&<p className="muted">No matching documents.</p>}</div>:<div className="library-empty"><div className="empty-file"><FileText size={34} strokeWidth={1}/><Plus size={15}/></div><h2>{restored?'Add your first PDF':'Opening your library…'}</h2><p>Drop a document here or import one to start reading.</p><button className="primary-button" disabled={importing} onClick={()=>input.current?.click()}>{importing?<LoaderCircle size={17} className="spin"/>:<Plus size={18}/>} {importing?'Importing…':'Import a PDF'}</button></div>}</main>:<div className="reader-shell">
      <aside className="sidebar"><button className="back-to-library" onClick={()=>setView('library')}><ArrowLeft size={20}/> Library</button><div className="sidebar-section-title">Pages</div><div className="chapter-list">{Array.from({length:doc.pages},(_,i)=>{const p=i+1;const m=mastery(annotations.filter(a=>a.selection.page===p));const confidence=m.total?m.correct/m.total:null;return <button key={p} className={p===page?'current':''} onClick={()=>{setPage(p);setSelection(null);}}><span>Page {p}</span>{annotations.some(a=>a.selection.page===p)&&<span className={`confidence ${confidence===null?'untouched':confidence>=.8?'high':confidence>=.5?'medium':'low'}`}/>}</button>;})}</div><div className="sidebar-bottom"><button className="text-button" onClick={()=>setModal('insights')}><GraduationCap size={17}/> Learning insights <span>{score.total?`${score.score}%`:'—'}</span></button></div></aside>
      <main className="main"><div className="document-heading"><div><h1>{doc.name.replace(/\.pdf$/i,'')}</h1><p>{doc.pages||'…'} pages{roomId?' · Shared room':''}</p></div><button className="icon-button" disabled={sharing} aria-label="Share study room" onClick={share}>{sharing?<LoaderCircle size={19} className="spin"/>:<Share2 size={19}/>}</button></div>
      <div className="workspace"><PdfReader key={doc.id} document={doc} page={page} onPage={p=>{setPage(Math.max(1,Math.min(doc.pages||1,p)));setSelection(null);}} onSelection={setSelection} selected={selection} annotations={annotations} onError={onError} onLoaded={(pages,text)=>{setPageText(text);if(doc.pages!==pages)updateDoc(doc.id,d=>({...d,pages}));}}/>
        <aside className="annotation-rail"><div className="rail-heading"><div><Sparkles size={18}/><h2>Your margin notes</h2></div><span>{annotations.length}</span></div>
          <div className={`selection-panel ${selection?'has-selection':''}`}><p className="eyebrow">{selection?`PAGE ${selection.page} · SELECTED`:'SELECT A PASSAGE'}</p>{selection?<><p className="selected-passage">{selection.image?'Selected area of your PDF':selection.text.slice(0,210)+(selection.text.length>210?'…':'')}</p><button className="clear-selection" aria-label="Clear selection" onClick={()=>{setSelection(null);window.getSelection()?.removeAllRanges();}}><X size={14}/></button></>:<p>Highlight text or select an area of your PDF.</p>}<div className="action-buttons">{(['adapt','quiz','animate'] as const).map(action=>{const Icon=actionIcons[action];return <button className={action} key={action} disabled={!selection||!!busy} onClick={()=>void generate(action)}>{busy===action?<LoaderCircle size={16} className="spin"/>:<Icon size={16}/>} {actionLabels[action]}</button>;})}</div>
            <div className="learning-controls"><label>Level<select aria-label="Reading level" value={prefs.level} onChange={e=>setPrefs({...prefs,level:e.target.value as Preferences['level']})}>{levels.map(l=><option key={l}>{l}</option>)}</select></label><label>Language<select aria-label="Explanation language" value={prefs.language} onChange={e=>setPrefs({...prefs,language:e.target.value as Preferences['language']})}>{languages.map(l=><option key={l}>{l}</option>)}</select></label></div>
          </div>
          <div className="rail-tabs" role="tablist" aria-label="Annotation filters">{(['all','adapt','quiz','animate','review'] as const).map(t=><button role="tab" aria-selected={tab===t} key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t==='all'?'All notes':t==='review'?`Review${due.length?` (${due.length})`:''}`:actionLabels[t]}</button>)}</div>
          <div className="rail-scroll">{busy&&busy!=='study-pack'&&<div className="generation-loading" role="status"><LoaderCircle className="spin" size={20}/><strong>{busy==='adapt'?'Finding a clearer way to explain it…':busy==='quiz'?'Building your knowledge check…':busy==='animate'?'Connecting the visual story…':'Finding the foundations…'}</strong><div className="skeleton"/><div className="skeleton"/><div className="skeleton short"/></div>}
            {filtered.length?filtered.map(a=><AnnotationCard key={a.id} annotation={a} own={ownIds.has(a.id)} onChange={updateAnnotation} onError={onError} onPage={p=>{setPage(Math.max(1,Math.min(doc.pages||1,p)));setSelection(null);}} onPrerequisites={()=>void generate('prerequisites',{...a.selection})} voiceId={voiceId} autoNarrate={prefs.autoNarrate&&!!health?.elevenlabs.configured} reviewMode={tab==='review'}/>):<div className="empty-notes"><BookOpen size={25} strokeWidth={1.2}/><h3>{tab==='review'?'Nothing to review':'No annotations yet'}</h3><p>{tab==='review'?'Missed questions return after 24 hours.':'Select something in your PDF to get started.'}</p></div>}
          </div><div className="rail-footer"><span>{busy?'Generating…':'Saved to your library'}</span><button className="icon-button" aria-label="API configuration" onClick={()=>setModal('settings')}><Settings2 size={15}/></button></div>
        </aside></div></main></div>}
    {modal==='import'&&<Modal title="Add a reading" onClose={()=>setModal(null)}><button className="upload-zone" disabled={importing} onClick={()=>input.current?.click()}><Upload size={30}/><strong>{importing?'Opening your PDF…':'Choose a PDF or drop it here'}</strong><span>Up to 30 MB · saved in this browser</span></button><div className="divider">or import from a link</div><form onSubmit={e=>{e.preventDefault();void importUrl();}}><label className="field-label" htmlFor="pdf-url">PDF URL</label><div className="inline-input"><input id="pdf-url" type="url" required placeholder="https://example.edu/reading.pdf" value={url} onChange={e=>setUrl(e.target.value)}/><button className="primary-button" disabled={importing}>{importing?<LoaderCircle size={16} className="spin"/>:'Import'}</button></div><p className="help">Some sites block direct imports. If that happens, download the PDF and upload it.</p></form>{error&&<p className="inline-error" role="alert">{error}</p>}</Modal>}
    {modal==='settings'&&<Modal title="Your tutor, your way" onClose={()=>setModal(null)}><div className="settings-grid"><label>Your display name<input maxLength={60} value={prefs.name} onChange={e=>setPrefs({...prefs,name:e.target.value})}/></label><label>Tutor voice<select value={voiceId} onChange={e=>setPrefs({...prefs,voiceId:e.target.value})}><option value={health?.elevenlabs.voiceId||''}>Default tutor voice</option>{voices.filter(v=>v.id!==health?.elevenlabs.voiceId).map(v=><option value={v.id} key={v.id}>{v.name}</option>)}</select></label></div><button className="small-button" disabled={voiceLoading||!health?.elevenlabs.configured} onClick={async()=>{setVoiceLoading(true);try{setVoices(await api('/voices'));}catch(e){onError((e as Error).message);}finally{setVoiceLoading(false);}}}><Volume2 size={15}/>{voiceLoading?'Loading voices…':'Load my ElevenLabs voices'}</button><label className="checkbox-label"><input type="checkbox" checked={prefs.autoNarrate} onChange={e=>setPrefs({...prefs,autoNarrate:e.target.checked})}/> Automatically narrate new adaptations</label><div className="api-status"><h3>API connections</h3>{[['Gemini',health?.gemini.configured,health?.gemini.model],['ElevenLabs',health?.elevenlabs.configured,health?.elevenlabs.model]].map(([name,configured,model])=><div key={String(name)}><span>{name}<small>{model||'Checking server…'}</small></span><strong className={configured?'configured':'missing'}>{configured?'Key configured':'Key needed'}</strong></div>)}<p>Add your keys to <code>.env</code> in the project folder and restart the server.</p><pre>GEMINI_API_KEY=your_key{'\n'}ELEVENLABS_API_KEY=your_key</pre><p className="help">Keys stay on the server. “Configured” checks their presence; the first request verifies account access. Selected text and figure crops go to Gemini; narration text goes to ElevenLabs.</p><button className="text-button" onClick={async()=>{try{setHealth(await api('/health'));setNotice('Connection configuration refreshed.');}catch(e){onError((e as Error).message);}}}><RotateCcw size={14}/> Refresh configuration</button></div>{error&&<p className="inline-error" role="alert">{error}</p>}</Modal>}
    {modal==='share'&&<Modal title="Study together" onClose={()=>setModal(null)}><p>Anyone with this link can view and add annotations in this study room. Each person imports the same PDF; the PDF file stays in their browser.</p><label className="field-label" htmlFor="room-link">Study room link</label><input id="room-link" readOnly value={`${location.origin}/?room=${roomId||''}`}/><button className="primary-button" onClick={async()=>{try{await navigator.clipboard.writeText(`${location.origin}/?room=${roomId}`);setCopied(true);}catch{onError('Clipboard unavailable. Select and copy the link above.');}}}><Share2 size={15}/>{copied?'Link copied':'Copy link'}</button><p className="help">A localhost link works on this computer. For another device, run the server on a reachable host and share its address. Rooms are refreshed every five seconds.</p></Modal>}
    {modal==='insights'&&<Modal title="Learning insights" onClose={()=>setModal(null)}><div className="insight-summary"><div><strong>{score.score}<small>/100</small></strong><span>Your understanding score</span></div><div><strong>{score.total?Math.round(score.correct/score.total*100):'—'}<small>{score.total?'%':''}</small></strong><span>Your quiz accuracy</span></div><div><strong>{new Set(annotations.map(a=>a.author)).size}</strong><span>Contributors</span></div></div><p className="help">Quiz accuracy contributes up to 80 points. Adaptations add 4 points each and completed explainers add 6, capped at 20 engagement points. Activity alone does not measure mastery.</p><h3>Instructor view · {roomId?'Study room':'This browser'}</h3><p className="help">Page results below aggregate answered quizzes from all visible annotations.</p><div className="insight-table"><table><thead><tr><th>Section</th><th>Answers</th><th>Accuracy</th><th>Confidence</th></tr></thead><tbody>{Array.from({length:doc?.pages||0},(_,i)=>{const m=mastery(annotations.filter(a=>a.selection.page===i+1));const fraction=m.total?m.correct/m.total:0;return <tr key={i}><td><button className="text-button" onClick={()=>{setPage(i+1);setModal(null);}}>Page {i+1}</button></td><td>{m.total}</td><td>{m.total?`${Math.round(fraction*100)}%`:'—'}</td><td>{m.total?fraction>=.8?'Strong':fraction>=.5?'Building':'Review recommended':'Not assessed'}</td></tr>;})}</tbody></table></div>{!annotations.length&&<p>Generate a quiz to start measuring understanding.</p>}</Modal>}
    {modal==='pack'&&<Modal title="Your study pack" onClose={()=>setModal(null)}>{busy==='study-pack'?<div className="generation-loading" role="status"><LoaderCircle size={24} className="spin"/><p>Connecting your notes into a review guide…</p><div className="skeleton"/><div className="skeleton"/></div>:pack?<><h3>{pack.title}</h3><Markdown>{pack.summary}</Markdown><h3>Key ideas</h3><ul>{pack.keyIdeas.map((idea,i)=><li key={i}>{idea}</li>)}</ul><button className="primary-button" onClick={()=>doc&&exportPack(doc.name,pack,annotations)}><Download size={16}/> Download study pack</button><p className="help">A standalone HTML guide with a printable summary, linked notes, answerable quizzes, and explainer storyboards.</p></>:<><p className="inline-error" role="alert">{error||'The study pack could not be generated.'}</p><button className="primary-button" onClick={generatePack}>Try again</button></>}</Modal>}
  </div>;
}
